from typing import Any, Protocol

class MobileClient(Protocol):
    def launch_app(self, bundle_id: str) -> None: ...
    def get_ui_tree(self) -> Any: ...
    def take_screenshot(self, path: str) -> None: ...
    def tap(self, x: int, y: int) -> None: ...
    def type_text(self, text: str) -> None: ...
    def swipe(self, start: tuple[int, int], end: tuple[int, int]) -> None: ...
    def press_back(self) -> None: ...
    def foreground_app(self) -> str | None: ...

class UnconfiguredMobileClient:
    """Explicit adapter seam; production wiring belongs to Mobile MCP/devicekit."""
    def __getattr__(self, name: str):
        raise RuntimeError("Mobile MCP/devicekit client is not configured")

